server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
  server:
    enableSelfPreservation: false
spring:
  application:
    name: cyber-done-discovery-microservice